object_classes:

  #--------------------------------------------------------------------------------------------
  # for car category 
  #--------------------------------------------------------------------------------------------
  car:
    keypoints_num: 12
    object_keypoints_mean:
      [-0.568, 0.568, 0.482, -0.482, -0.582,
      0.582, 0.702, -0.702, -0.805, -0.805,
      0.805, 0.805,
      -0.253, -0.253, 1.570, 1.570, -1.988,
      -1.988, 1.961, 1.961, -1.286, 1.355,
      -1.286, 1.355,
      1.331, 1.331, 1.331, 1.331, 0.702,
      0.702, 0.924, 0.924, 0.329, 0.329,
      0.329, 0.329]
    object_mean_shape:
      [1.6, 3.9, 1]
    aliases:
      - truck
      - bus
      - van
    marker_color: [0.0, 0.0, 0.0]
    # color is black 

  #--------------------------------------------------------------------------------------------
  # for door category 
  #--------------------------------------------------------------------------------------------

  door:
    keypoints_num: 4
    object_keypoints_mean:
      [-1.25, 1.25, 1.25, -1.25,
      0, 0, 0, 0,
      -1.25, -1.25, 1.25, 1.25]
    object_mean_shape:
      [2.5, 1, 2.5]
    # door_object_mean_shape:
    #   [2.5, 0.2, 2.5]
    aliases: []
    marker_color: [1.0, 0.0, 0.0]
    # color is red 

  #--------------------------------------------------------------------------------------------
  # for barrier category 
  #--------------------------------------------------------------------------------------------
  
  barrier:
    keypoints_num: 8
    object_keypoints_mean:
      [0.38, 0.38, 0.1, 0.1, -0.38, -0.38, -0.1, -0.1,
        2, -2, -2, 2, 2, -2, -2, 2, 
        0, 0, 1, 1, 0, 0, 1, 1]
    object_mean_shape:
      [0.76, 4, 1]
    aliases: []
    marker_color: [1.0, 0.5, 0.0]
    # orange 

  #--------------------------------------------------------------------------------------------
  # for pylon category 
  #--------------------------------------------------------------------------------------------

  pylon:
    keypoints_num: 5
    object_keypoints_mean:
      [0.38, 0.38, 0.1, 0.1, -0.38, 
      2, -2, -2, 2, 2,  
      0, 0, 1, 1, 0]
    object_mean_shape:
     [0.35, 0.35, 0.7]
    aliases: []
    marker_color: [0.0, 0.0, 1.0]
    # blue 

  #--------------------------------------------------------------------------------------------
  # for bicycle category 
  #--------------------------------------------------------------------------------------------

  bicycle:
    keypoints_num: 11
    object_keypoints_mean:
      [-1.70808127e-04,  -1.50001940e-01,   1.49998060e-01,
         -2.81705415e-02,   2.92172366e-02,  -1.72628652e-04,
         -1.55280115e-05,  -3.59743247e-02,   3.24773351e-02,
         -4.51876315e-02,   3.94705946e-02,
       -5.44494399e-01,  -5.57207036e-01,  -5.59112866e-01,
         -8.99557479e-01,  -8.99540561e-01,   6.89689240e-01,
          1.30573382e-01,   9.00442521e-01,   8.94981261e-01,
          7.94408375e-02,   8.24049428e-02,
       6.78173161e-01,   6.59279873e-01,   6.58873971e-01,
         -2.86543426e-01,  -2.86444976e-01,   5.80824071e-01,
          5.95945049e-01,  -2.77740430e-01,  -2.78488707e-01,
         -3.21826839e-01,  -3.18725364e-01]
    object_mean_shape:
      [0.3, 1.8, 1.0]
    aliases: []
    marker_color: [0.5, 0.0, 0.5]
    # purple 

  #--------------------------------------------------------------------------------------------
  # for diningtable category 
  #--------------------------------------------------------------------------------------------

  diningtable:
    keypoints_num: 12
    object_keypoints_mean:
      [-0.50076262,  0.49923738,  0.49863652, -0.49998704, -0.4602089 ,
          0.45837508,  0.45904081, -0.4593491 ,  0.        , -0.08486342,
          0.        ,  0.08486342,
        0.49879703,  0.49844009, -0.49978185, -0.50120297,  0.39109233,
          0.3846282 , -0.43611014, -0.43722306,  0.13482467,  0.        ,
          -0.13482467,  0.        ,
        0.50415013,  0.50367867,  0.50415013,  0.50415013, -0.49584987,
          -0.4943489 , -0.49151052, -0.49151052,  0.15026394,  0.15026394,
          0.15026394,  0.15026394]
    object_mean_shape:
      [1, 1, 1]
    aliases: []
    marker_color: [0.5, 0.5, 0.5]
    # gray 

  #--------------------------------------------------------------------------------------------
  # for chair category 
  #--------------------------------------------------------------------------------------------

  chair:
    keypoints_num: 10
    object_keypoints_mean:
      [-0.16260029, -0.18636511,  0.16428348,  0.18096888, -0.174444  ,
            -0.19166636,  0.1767874 ,  0.18786542, -0.19818088,  0.19658388,
      0.17052046,  0.13219248,  0.17011265,  0.13199527, -0.19604203,
            -0.21056669, -0.19605567, -0.20875473,  0.19473798,  0.19352854,
      -0.44795494, -0.00819907, -0.44773116, -0.00803745, -0.44755495,
            -0.01097987, -0.44755495, -0.01101388,  0.55173099,  0.55204506]
    object_mean_shape:
      [0.4, 0.4, 1]
    aliases:
      - bench
    marker_color: [0.0, 0.0, 1.0]
    # blue 

  #--------------------------------------------------------------------------------------------
  # for monitor category 
  #--------------------------------------------------------------------------------------------
  
  tvmonitor:
    keypoints_num: 8
    object_keypoints_mean:
      [-0.24979928,  0.25018418, -0.24980799,  0.25019201, -0.07860816,
         0.07860816, -0.07860816,  0.07860816,
       -0.02643643, -0.0264397 , -0.02643432, -0.02643994,  0.02356006,
         0.02356006,  0.02356006,  0.02356006,
       -0.22036003, -0.22037013,  0.27962987,  0.27961471, -0.07454422,
        -0.07454422,  0.07585024,  0.07585024]
    object_mean_shape:
      [0.5, 0.05, 0.5]
    aliases: 
      - computer 
      - laptop 
    marker_color: [1.0, 0.0, 0.0]
    # red 


#--------------------------------------------------------------------------------------------
# other configs 
#--------------------------------------------------------------------------------------------

# whether to fine tune object pose using Levenberg Marquardt
# do_fine_tune_object_pose_using_lm: false 
do_fine_tune_object_pose_using_lm: true       

# The directory where result files are saved per object
result_dir_path_object_map: "$(env HOME)/.ros/log/orcvio-backend/results/"
# result_dir_path_object_map: "/home/erl/Workspace/orcvio_cpp/cache/object_map/"

#--------------------------------------------------------------------------------------------
# groundtruth object states 
#--------------------------------------------------------------------------------------------

# note, these cannot be empty even if we don't have groundtruth object states

total_object_num: 22

objects_ids_gt: [1, 4, 7, 10, 13, 16, 1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13, 14,
    15, 16, 17]

objects_class_gt: [chair, chair, chair, chair, chair, chair, chair, chair, tvmonitor, tvmonitor, tvmonitor, tvmonitor,
    tvmonitor, tvmonitor, tvmonitor, tvmonitor, tvmonitor, tvmonitor, tvmonitor, tvmonitor, tvmonitor, tvmonitors]

objects_rotation_gt:
  [2.220446049250313e-16, 1.0, 0.0, -1.0, 2.220446049250313e-16,
    -0.0, -0.0, 0.0, 1.0, 2.220446049250313e-16, 1.0, 0.0, -1.0, 2.220446049250313e-16,
    -0.0, -0.0, 0.0, 1.0, 2.220446049250313e-16, 1.0, 0.0, -1.0, 2.220446049250313e-16,
    -0.0, -0.0, 0.0, 1.0, 2.220446049250313e-16, 1.0, 0.0, -1.0, 2.220446049250313e-16,
    -0.0, -0.0, 0.0, 1.0, 2.220446049250313e-16, 1.0, 0.0, -1.0, 2.220446049250313e-16,
    -0.0, -0.0, 0.0, 1.0, 2.220446049250313e-16, 1.0, 0.0, -1.0, 2.220446049250313e-16,
    -0.0, -0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0,
    0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0,
    0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0,
    1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0,
    0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0,
    1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0008028513696686779,
    0.9999996777147871, 0.0, -0.9999996777147871, 0.0008028513696686779, -0.0, -0.0,
    0.0, 1.0, 0.0008028513696686779, 0.9999996777147871, 0.0, -0.9999996777147871,
    0.0008028513696686779, -0.0, -0.0, 0.0, 1.0, 0.0008028513696686779, 0.9999996777147871,
    0.0, -0.9999996777147871, 0.0008028513696686779, -0.0, -0.0, 0.0, 1.0, 0.0008028513696686779,
    0.9999996777147871, 0.0, -0.9999996777147871, 0.0008028513696686779, -0.0, -0.0,
    0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0,
    0.0, 0.0, 0.0, 1.0]

objects_translation_gt:
  [5.0, 5.5, 0.0, 20.0, 0.5, 0.0, 35.0, 5.5, 0.0, -35.0, 5.5,
    0.0, -15.0, 5.5, 0.0, -30.0, 0.5, 0.0, -49.09, -10.76, 1.57, -29.59, -14.41, 1.57,
    -26.561, -14.41, 1.57, -8.986, 10.935, 1.602, -5.21, 10.935, 1.602, -5.547, -4.08,
    1.602, -1.66, -4.08, 1.602, 12.78, -4.519, 1.602, 12.461, 17.475, 1.602, 15.332,
    17.475, 1.602, 17.3, 12.505, 1.602, 17.3, 15.349, 1.602, 27.47, -5.178, 1.602,
    27.47, -8.96, 1.602, -49.14, -10.74, 1.63, -38.582, 13.98, 1.63]

first_uav_translation_gt:
  [1, 1, 0.3]
